my-app {
  routes {
    # If ask takes more time than this to complete the request is failed
    ask-timeout = 120s
  }
}

akka {
  http {
    server {
      request-timeout = 120s
      idle-timeout = 120s
    }
    client {
      connecting-timeout = 30s
      idle-timeout = 120s
    }
    host-connection-pool {
      idle-timeout = 120s
      response-entity-subscription-timeout = 120s
    }
  }
}

